#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.82.6.

use crate::api::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::rust2dart::IntoIntoDart;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_deploy_contract_impl(
    port_: MessagePort,
    private_key: impl Wire2Api<String> + UnwindSafe,
    node_url: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "deploy_contract",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_private_key = private_key.wire2api();
            let api_node_url = node_url.wire2api();
            move |task_callback| Result::<_, ()>::Ok(deploy_contract(api_private_key, api_node_url))
        },
    )
}
fn wire_get_script_impl(
    port_: MessagePort,
    private_key: impl Wire2Api<String> + UnwindSafe,
    node_url: impl Wire2Api<String> + UnwindSafe,
    contract_id_str: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, [u8; 32], _>(
        WrapInfo {
            debug_name: "get_script",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_private_key = private_key.wire2api();
            let api_node_url = node_url.wire2api();
            let api_contract_id_str = contract_id_str.wire2api();
            move |task_callback| {
                Result::<_, ()>::Ok(get_script(
                    api_private_key,
                    api_node_url,
                    api_contract_id_str,
                ))
            }
        },
    )
}
fn wire_get_predicate_address_impl(
    port_: MessagePort,
    wallet_public_key: impl Wire2Api<String> + UnwindSafe,
    script_hash: impl Wire2Api<[u8; 32]> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "get_predicate_address",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_wallet_public_key = wallet_public_key.wire2api();
            let api_script_hash = script_hash.wire2api();
            move |task_callback| {
                Result::<_, ()>::Ok(get_predicate_address(
                    api_wallet_public_key,
                    api_script_hash,
                ))
            }
        },
    )
}
fn wire_gen_transfer_tx_request_impl(
    port_: MessagePort,
    node_url: impl Wire2Api<String> + UnwindSafe,
    wallet_public_key: impl Wire2Api<String> + UnwindSafe,
    script_hash: impl Wire2Api<[u8; 32]> + UnwindSafe,
    to: impl Wire2Api<String> + UnwindSafe,
    amount: impl Wire2Api<u64> + UnwindSafe,
    asset: impl Wire2Api<String> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, (Vec<u8>, Vec<u8>), _>(
        WrapInfo {
            debug_name: "gen_transfer_tx_request",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_node_url = node_url.wire2api();
            let api_wallet_public_key = wallet_public_key.wire2api();
            let api_script_hash = script_hash.wire2api();
            let api_to = to.wire2api();
            let api_amount = amount.wire2api();
            let api_asset = asset.wire2api();
            move |task_callback| {
                Result::<_, ()>::Ok(gen_transfer_tx_request(
                    api_node_url,
                    api_wallet_public_key,
                    api_script_hash,
                    api_to,
                    api_amount,
                    api_asset,
                ))
            }
        },
    )
}
fn wire_send_tx_impl(
    port_: MessagePort,
    node_url: impl Wire2Api<String> + UnwindSafe,
    encoded_tx: impl Wire2Api<Vec<u8>> + UnwindSafe,
    signature: impl Wire2Api<Vec<u8>> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap::<_, _, _, String, _>(
        WrapInfo {
            debug_name: "send_tx",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_node_url = node_url.wire2api();
            let api_encoded_tx = encoded_tx.wire2api();
            let api_signature = signature.wire2api();
            move |task_callback| {
                Result::<_, ()>::Ok(send_tx(api_node_url, api_encoded_tx, api_signature))
            }
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u64> for u64 {
    fn wire2api(self) -> u64 {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

// Section: impl IntoDart

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    use super::*;
    // Section: wire functions

    #[wasm_bindgen]
    pub fn wire_deploy_contract(port_: MessagePort, private_key: String, node_url: String) {
        wire_deploy_contract_impl(port_, private_key, node_url)
    }

    #[wasm_bindgen]
    pub fn wire_get_script(
        port_: MessagePort,
        private_key: String,
        node_url: String,
        contract_id_str: String,
    ) {
        wire_get_script_impl(port_, private_key, node_url, contract_id_str)
    }

    #[wasm_bindgen]
    pub fn wire_get_predicate_address(
        port_: MessagePort,
        wallet_public_key: String,
        script_hash: Box<[u8]>,
    ) {
        wire_get_predicate_address_impl(port_, wallet_public_key, script_hash)
    }

    #[wasm_bindgen]
    pub fn wire_gen_transfer_tx_request(
        port_: MessagePort,
        node_url: String,
        wallet_public_key: String,
        script_hash: Box<[u8]>,
        to: String,
        amount: u64,
        asset: String,
    ) {
        wire_gen_transfer_tx_request_impl(
            port_,
            node_url,
            wallet_public_key,
            script_hash,
            to,
            amount,
            asset,
        )
    }

    #[wasm_bindgen]
    pub fn wire_send_tx(
        port_: MessagePort,
        node_url: String,
        encoded_tx: Box<[u8]>,
        signature: Box<[u8]>,
    ) {
        wire_send_tx_impl(port_, node_url, encoded_tx, signature)
    }

    // Section: allocate functions

    // Section: related functions

    // Section: impl Wire2Api

    impl Wire2Api<String> for String {
        fn wire2api(self) -> String {
            self
        }
    }

    impl Wire2Api<[u8; 32]> for Box<[u8]> {
        fn wire2api(self) -> [u8; 32] {
            let vec: Vec<u8> = self.wire2api();
            support::from_vec_to_array(vec)
        }
    }
    impl Wire2Api<Vec<u8>> for Box<[u8]> {
        fn wire2api(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    // Section: impl Wire2Api for JsValue

    impl<T> Wire2Api<Option<T>> for JsValue
    where
        JsValue: Wire2Api<T>,
    {
        fn wire2api(self) -> Option<T> {
            (!self.is_null() && !self.is_undefined()).then(|| self.wire2api())
        }
    }
    impl Wire2Api<String> for JsValue {
        fn wire2api(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl Wire2Api<u64> for JsValue {
        fn wire2api(self) -> u64 {
            ::std::convert::TryInto::try_into(self.dyn_into::<js_sys::BigInt>().unwrap()).unwrap()
        }
    }
    impl Wire2Api<u8> for JsValue {
        fn wire2api(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }
    impl Wire2Api<[u8; 32]> for JsValue {
        fn wire2api(self) -> [u8; 32] {
            let vec: Vec<u8> = self.wire2api();
            support::from_vec_to_array(vec)
        }
    }
    impl Wire2Api<Vec<u8>> for JsValue {
        fn wire2api(self) -> Vec<u8> {
            self.unchecked_into::<js_sys::Uint8Array>().to_vec().into()
        }
    }
}
#[cfg(target_family = "wasm")]
pub use self::web::*;

#[cfg(not(target_family = "wasm"))]
mod io {
    use super::*;
    // Section: wire functions

    #[no_mangle]
    pub extern "C" fn wire_deploy_contract(
        port_: i64,
        private_key: *mut wire_uint_8_list,
        node_url: *mut wire_uint_8_list,
    ) {
        wire_deploy_contract_impl(port_, private_key, node_url)
    }

    #[no_mangle]
    pub extern "C" fn wire_get_script(
        port_: i64,
        private_key: *mut wire_uint_8_list,
        node_url: *mut wire_uint_8_list,
        contract_id_str: *mut wire_uint_8_list,
    ) {
        wire_get_script_impl(port_, private_key, node_url, contract_id_str)
    }

    #[no_mangle]
    pub extern "C" fn wire_get_predicate_address(
        port_: i64,
        wallet_public_key: *mut wire_uint_8_list,
        script_hash: *mut wire_uint_8_list,
    ) {
        wire_get_predicate_address_impl(port_, wallet_public_key, script_hash)
    }

    #[no_mangle]
    pub extern "C" fn wire_gen_transfer_tx_request(
        port_: i64,
        node_url: *mut wire_uint_8_list,
        wallet_public_key: *mut wire_uint_8_list,
        script_hash: *mut wire_uint_8_list,
        to: *mut wire_uint_8_list,
        amount: u64,
        asset: *mut wire_uint_8_list,
    ) {
        wire_gen_transfer_tx_request_impl(
            port_,
            node_url,
            wallet_public_key,
            script_hash,
            to,
            amount,
            asset,
        )
    }

    #[no_mangle]
    pub extern "C" fn wire_send_tx(
        port_: i64,
        node_url: *mut wire_uint_8_list,
        encoded_tx: *mut wire_uint_8_list,
        signature: *mut wire_uint_8_list,
    ) {
        wire_send_tx_impl(port_, node_url, encoded_tx, signature)
    }

    // Section: allocate functions

    #[no_mangle]
    pub extern "C" fn new_uint_8_list_0(len: i32) -> *mut wire_uint_8_list {
        let ans = wire_uint_8_list {
            ptr: support::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        support::new_leak_box_ptr(ans)
    }

    // Section: related functions

    // Section: impl Wire2Api

    impl Wire2Api<String> for *mut wire_uint_8_list {
        fn wire2api(self) -> String {
            let vec: Vec<u8> = self.wire2api();
            String::from_utf8_lossy(&vec).into_owned()
        }
    }

    impl Wire2Api<[u8; 32]> for *mut wire_uint_8_list {
        fn wire2api(self) -> [u8; 32] {
            let vec: Vec<u8> = self.wire2api();
            support::from_vec_to_array(vec)
        }
    }
    impl Wire2Api<Vec<u8>> for *mut wire_uint_8_list {
        fn wire2api(self) -> Vec<u8> {
            unsafe {
                let wrap = support::box_from_leak_ptr(self);
                support::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    // Section: wire structs

    #[repr(C)]
    #[derive(Clone)]
    pub struct wire_uint_8_list {
        ptr: *mut u8,
        len: i32,
    }

    // Section: impl NewWithNullPtr

    pub trait NewWithNullPtr {
        fn new_with_null_ptr() -> Self;
    }

    impl<T> NewWithNullPtr for *mut T {
        fn new_with_null_ptr() -> Self {
            std::ptr::null_mut()
        }
    }

    // Section: sync execution mode utility

    #[no_mangle]
    pub extern "C" fn free_WireSyncReturn(ptr: support::WireSyncReturn) {
        unsafe {
            let _ = support::box_from_leak_ptr(ptr);
        };
    }
}
#[cfg(not(target_family = "wasm"))]
pub use self::io::*;
