name: flutter_fuelet_smart_contract_wallet
description: Flutter bridge for Fuelet smart contract wallet
version: 0.0.5
homepage: https://github.com/Fuelet/SmartContractWalletSDK

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  fuelet_smart_contract_wallet: ^1.2.0
  convert: ^3.1.1

dev_dependencies:
  ffi: ^2.0.1
  ffigen: ^6.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
