name: Initialize
description: Common steps for initialization

runs:
  using: composite
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.16.4

    - name: Setup Melos
      uses: bluefireteam/melos-action@v2
      with:
        melos-version: 3.4.0

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2

    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15"

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
