[package]
name = "fuelet_smart_contract_wallet"
version = "0.0.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.6"
hex = "0.4.3"
serde_json = "1.0.113"

[dependencies]
flutter_rust_bridge = "1.82.6"
fuels = "0.63.1"
fuel-tx = "0.50.0" # must be compatible with the fuels version
fuel-crypto = "0.50.0" # must be compatible with the fuels version
tokio = "1.14.0"
sha2 = "0.10.8"
hex = "0.4.3"
tempfile = "3.2.0"
