name: fuelet_smart_contract_wallet
description: Dart bridge for Fuelet smart contract wallet
version: 1.2.1
repository: https://github.com/Fuelet/SmartContractWalletSDK

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  flutter_rust_bridge: 1.82.6
  uuid: ^4.2.1 # must be compatible with flutter_rust_bridge version
  meta: ^1.8.0

dev_dependencies:
  ffigen: ^9.0.1
  lints: ^2.0.0
  test: ^1.24.2
