name: Run flutter_rust_bridge codegen

on: workflow_dispatch

permissions:
  contents: write

jobs:
  codegen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/initialize

      - name: Install FRB
        run: cargo install --version 1.82.6 flutter_rust_bridge_codegen

      - name: Install cargo-expand
        run: cargo install cargo-expand

      - name: FRB codegen
        run: cargo build

      - name: Build web
        run: melos run build:web

      - name: Commit
        run: |
          git add -A
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git commit -am "Codegen" || echo "Nothing to commit"
          git push || echo "Nothing to push"
